/usr/local/lib/python3.5/imp.py:216: FutureWarning: The pandas.rpy module is deprecated and will be removed in a future version. We refer to external packages like rpy2. 
See here for a guide on how to port your code to rpy2: http://pandas.pydata.org/pandas-docs/stable/r_interface.html
  return _load(spec)
/usr/local/lib/python3.5/site-packages/matplotlib-1.5.1-py3.5-linux-x86_64.egg/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/usr/local/lib/python3.5/site-packages/matplotlib-1.5.1-py3.5-linux-x86_64.egg/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
..............................................................................................................................S.......S.......S.......S.........................................................................................................................................................................................................................................................................................................................................................S.............S...............SSSSSSSSSS............................................S................................S.......................................................................................................SS...........................................S................................S.......................................................................................................SS...........................................................S................................................................................................SS.............................................S.....S..S...SS...S.S.SSS..........S........S......SS......................S.........SS.....................SS...............................S..........................SS...................................SS...................................SS..................SS.....................S...............................S........SS.........................S...............................S..SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...........E....................................EE...........................SS...SS..S................................................SSSSSS................................................................................S....................................S.........................S....................................................S../usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/util/testing.py:2162: FutureWarning: tquery is deprecated, and will be removed in future versions. You can use ``execute(...).fetchall()`` instead.
  _callable(*args, **kwargs)
../usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/io/tests/test_sql.py:2445: FutureWarning: tquery is deprecated, and will be removed in future versions. You can use ``execute(...).fetchall()`` instead.
  self.assertEqual(sql.tquery(sql_select, con=self.conn),
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/io/tests/test_sql.py:2449: FutureWarning: tquery is deprecated, and will be removed in future versions. You can use ``execute(...).fetchall()`` instead.
  self.assertEqual(sql.tquery(sql_select, con=self.conn),
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/io/tests/test_sql.py:2456: FutureWarning: tquery is deprecated, and will be removed in future versions. You can use ``execute(...).fetchall()`` instead.
  self.assertEqual(sql.tquery(sql_select, con=self.conn),
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/io/tests/test_sql.py:2460: FutureWarning: tquery is deprecated, and will be removed in future versions. You can use ``execute(...).fetchall()`` instead.
  self.assertEqual(sql.tquery(sql_select, con=self.conn),
...../usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/io/tests/test_sql.py:2354: FutureWarning: tquery is deprecated, and will be removed in future versions. You can use ``execute(...).fetchall()`` instead.
  result = sql.tquery("select A from test_table", self.conn)
./usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/io/tests/test_sql.py:2373: FutureWarning: uquery is deprecated, and will be removed in future versions. You can use ``execute(...).rowcount`` instead.
  self.assertEqual(sql.uquery(stmt, con=self.conn), 1)
./usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/io/tests/test_sql.py:2239: FutureWarning: tquery is deprecated, and will be removed in future versions. You can use ``execute(...).fetchall()`` instead.
  sql.tquery(fmt_sql, cur=cur)
................................................./usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/io/tests/test_wb.py:49: FutureWarning: sort(....) is deprecated, use sort_index(.....)
  expected.sort(inplace=True)
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/io/tests/test_wb.py:52: FutureWarning: sort(....) is deprecated, use sort_index(.....)
  result.sort(inplace=True)
.SS./usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/io/wb.py:268: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  data = data.sort(columns='id')
.........................../usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/sparse/array.py:52: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  return _wrap_result(name, op(self.sp_values, other),
...................................................../usr/local/lib/python3.5/site-packages/numpy/lib/function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)
........................................................................................................................./usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/core/panel.py:410: FutureWarning: SparsePanel is deprecated and will be removed in a future version
  default_fill_value=fill_value)
............................/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/core/panel.py:410: FutureWarning: SparsePanel is deprecated and will be removed in a future version
  default_fill_value=fill_value)
.................S.........................../usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/util/validators.py:45: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  match = (arg_val_dict[key] == compat_args[key])
................................................S..SS.....SSSSSSSSSSSSSSSSSSSSSSSSSSS............................................................................................................................................................................................................................................................................................................................................................................................................................................................................S..S.......................................................................................................................................................................................................S..................................................S...S................................................................................................................................................................................................................................................SS................................../usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tseries/tests/test_plotting.py:1188: FutureWarning: .resample() is now a deferred operation
use .resample(...).mean() instead of .resample(...)
  ts.resample('D').plot(secondary_y=True, ax=ax)
............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................S.......................................................................................................................................................................................................................................S.............................................SSS.........E...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................S..............S...........................................SS.....S...SS.......S.S.......................SS.....S...SS.......S.S.............................................................................................................................................S...........................................................................................................................................................................................................................................................................................................................................................................................................................................................S......................................................................................................................................................................................................................................................................................................................................................S./usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/util/validators.py:45: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  match = (arg_val_dict[key] == compat_args[key])
.............S................................................................................................................./usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tseries/base.py:192: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  val = getitem(key)
................................................................................................................................................................................................................./usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/core/ops.py:995: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 1 but corresponding boolean dimension is 9
  yrav = yrav[mask]
...............S./usr/local/lib/python3.5/site-packages/numpy/lib/function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)
................................................................................................................................................................................................................................................................................................................................................................................................./usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/util/validators.py:45: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  match = (arg_val_dict[key] == compat_args[key])
.............S.....................S...........S.......S......S....S...../usr/local/lib/python3.5/site-packages/numpy/lib/function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)
.........................S................................................................................................../usr/local/lib/python3.5/site-packages/dateutil/rrule.py:470: DeprecationWarning: Using both 'count' and 'until' is inconsistent with RFC 2445 and has been deprecated in dateutil. Future versions will raise an error.
  "raise an error.", DeprecationWarning)
........./usr/local/lib/python3.5/site-packages/dateutil/rrule.py:470: DeprecationWarning: Using both 'count' and 'until' is inconsistent with RFC 2445 and has been deprecated in dateutil. Future versions will raise an error.
  "raise an error.", DeprecationWarning)
/usr/local/lib/python3.5/site-packages/dateutil/rrule.py:470: DeprecationWarning: Using both 'count' and 'until' is inconsistent with RFC 2445 and has been deprecated in dateutil. Future versions will raise an error.
  "raise an error.", DeprecationWarning)
/usr/local/lib/python3.5/site-packages/dateutil/rrule.py:470: DeprecationWarning: Using both 'count' and 'until' is inconsistent with RFC 2445 and has been deprecated in dateutil. Future versions will raise an error.
  "raise an error.", DeprecationWarning)
/usr/local/lib/python3.5/site-packages/dateutil/rrule.py:470: DeprecationWarning: Using both 'count' and 'until' is inconsistent with RFC 2445 and has been deprecated in dateutil. Future versions will raise an error.
  "raise an error.", DeprecationWarning)
/usr/local/lib/python3.5/site-packages/dateutil/rrule.py:470: DeprecationWarning: Using both 'count' and 'until' is inconsistent with RFC 2445 and has been deprecated in dateutil. Future versions will raise an error.
  "raise an error.", DeprecationWarning)
/usr/local/lib/python3.5/site-packages/dateutil/rrule.py:470: DeprecationWarning: Using both 'count' and 'until' is inconsistent with RFC 2445 and has been deprecated in dateutil. Future versions will raise an error.
  "raise an error.", DeprecationWarning)
/usr/local/lib/python3.5/site-packages/dateutil/rrule.py:470: DeprecationWarning: Using both 'count' and 'until' is inconsistent with RFC 2445 and has been deprecated in dateutil. Future versions will raise an error.
  "raise an error.", DeprecationWarning)
/usr/local/lib/python3.5/site-packages/dateutil/rrule.py:470: DeprecationWarning: Using both 'count' and 'until' is inconsistent with RFC 2445 and has been deprecated in dateutil. Future versions will raise an error.
  "raise an error.", DeprecationWarning)
.............../usr/local/lib/python3.5/site-packages/dateutil/rrule.py:470: DeprecationWarning: Using both 'count' and 'until' is inconsistent with RFC 2445 and has been deprecated in dateutil. Future versions will raise an error.
  "raise an error.", DeprecationWarning)
........./usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tests/test_graphics.py:780: PendingDeprecationWarning: generator 'TestSeriesPlots.test_pie_series.<locals>.<genexpr>' raised StopIteration
  expected_texts = list(next(it) for it in itertools.cycle(iters))
............/usr/local/lib/python3.5/site-packages/dateutil/rrule.py:470: DeprecationWarning: Using both 'count' and 'until' is inconsistent with RFC 2445 and has been deprecated in dateutil. Future versions will raise an error.
  "raise an error.", DeprecationWarning)
......./usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
./usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
./usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3352: UserWarning: When passing multiple axes, sharex and sharey are ignored. These settings must be specified when creating axes
  "when creating axes", UserWarning)
./usr/local/lib/python3.5/site-packages/matplotlib-1.5.1-py3.5-linux-x86_64.egg/matplotlib/artist.py:221: MatplotlibDeprecationWarning: This has been deprecated in mpl 1.5, please use the
axes property.  A removal date has not been set.
  warnings.warn(_get_axes_msg, mplDeprecation, stacklevel=1)
./usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
.......S/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
/usr/local/lib/python3.5/site-packages/matplotlib-1.5.1-py3.5-linux-x86_64.egg/matplotlib/artist.py:221: MatplotlibDeprecationWarning: This has been deprecated in mpl 1.5, please use the
axes property.  A removal date has not been set.
  warnings.warn(_get_axes_msg, mplDeprecation, stacklevel=1)
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
../usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
...../usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
....../usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
./usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tools/plotting.py:3369: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "the passed axes is being cleared", UserWarning)
....................................................................................................................................................................................................................................../usr/local/lib/python3.5/site-packages/numpy/lib/function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)
................................................................S........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................../usr/local/lib/python3.5/site-packages/nose/case.py:198: DeprecationWarning: fromstring() is deprecated. Use frombytes() instead.
  self.test(*self.arg)
..................../usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/msgpack/__init__.py:44: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  return Packer(**kwargs).pack(o)
/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tests/test_msgpack/test_extension.py:58: DeprecationWarning: fromstring() is deprecated. Use frombytes() instead.
  obj2 = msgpack.unpackb(s, ext_hook=ext_hook)
........................................................................................................................................S........................................................................................................S.........SS.................................................................................................................................................S...S.............SSS.........S...........SS...............SS.....SSSS............................................................................................................................................................................................./usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/core/common.py:332: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  return ((left == right) | (np.isnan(left) & np.isnan(right))).all()
........................................................................................................................................................S........................................................................................................................................................................................................................................................................................................................................................S.........................................................
======================================================================
ERROR: test_file_like (pandas.io.tests.test_html.TestReadHtml)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/io/tests/test_html.py", line 273, in test_file_like
    df1 = self.read_html(f, '.*Water.*')
  File "/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/io/tests/test_html.py", line 94, in read_html
    return read_html(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/io/html.py", line 874, in read_html
    parse_dates, tupleize_cols, thousands, attrs, encoding)
  File "/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/io/html.py", line 736, in _parse
    raise_with_traceback(retained)
  File "/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/compat/__init__.py", line 333, in raise_with_traceback
    raise exc.with_traceback(traceback)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 21552: ordinal not in range(128)

======================================================================
ERROR: test_string (pandas.io.tests.test_html.TestReadHtml)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/io/tests/test_html.py", line 264, in test_string
    data = f.read()
  File "/usr/local/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 21552: ordinal not in range(128)

======================================================================
ERROR: test_string_io (pandas.io.tests.test_html.TestReadHtml)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/io/tests/test_html.py", line 253, in test_string_io
    data1 = StringIO(f.read())
  File "/usr/local/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 21552: ordinal not in range(128)

======================================================================
ERROR: test_to_latex_filename (pandas.tests.formats.test_format.TestDataFrameFormatting)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/tests/formats/test_format.py", line 2721, in test_to_latex_filename
    df.to_latex(path)
  File "/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/core/frame.py", line 1602, in to_latex
    encoding=encoding)
  File "/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/formats/format.py", line 643, in to_latex
    latex_renderer.write_result(f)
  File "/usr/local/lib/python3.5/site-packages/pandas-0.18.1-py3.5-linux-x86_64.egg/pandas/formats/format.py", line 879, in write_result
    buf.write(' & '.join(crow))
UnicodeEncodeError: 'ascii' codec can't encode character '\xdf' in position 7: ordinal not in range(128)

----------------------------------------------------------------------
Ran 10138 tests in 1290.565s

FAILED (SKIP=206, errors=4)
True
Warning: discarding nonzero nanoseconds
Warning: discarding nonzero nanoseconds
Warning: discarding nonzero nanoseconds
Warning: discarding nonzero nanoseconds
Warning: discarding nonzero nanoseconds
Warning: discarding nonzero nanoseconds
Warning: discarding nonzero nanoseconds
Warning: discarding nonzero nanoseconds
Warning: discarding nonzero nanoseconds
Warning: discarding nonzero nanoseconds
Warning: discarding nonzero nanoseconds
Warning: discarding nonzero nanoseconds
Warning: discarding nonzero nanoseconds
Warning: discarding nonzero nanoseconds
Warning: discarding nonzero nanoseconds
Warning: discarding nonzero nanoseconds
Warning: discarding nonzero nanoseconds
Warning: discarding nonzero nanoseconds
Warning: discarding nonzero nanoseconds
Warning: discarding nonzero nanoseconds
Warning: discarding nonzero nanoseconds
Warning: discarding nonzero nanoseconds
Warning: discarding nonzero nanoseconds
Warning: discarding nonzero nanoseconds
Warning: discarding nonzero nanoseconds
Warning: discarding nonzero nanoseconds
Warning: discarding nonzero nanoseconds
Warning: discarding nonzero nanoseconds
Warning: discarding nonzero nanoseconds
Warning: discarding nonzero nanoseconds
Warning: discarding nonzero nanoseconds
Warning: discarding nonzero nanoseconds
WHAT THE
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 2 columns):
int64       2500 non-null int64
category    2500 non-null category
dtypes: category(1), int64(1)
memory usage: 22.1 KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 275 entries, 0 to 2499
Data columns (total 2 columns):
int64       275 non-null int64
category    275 non-null category
dtypes: category(1), int64(1)
memory usage: 4.6 KB
zounds!
default called array('d', [1.1, 2.2, 3.3])
ext_hook called 123 b'\x9a\x99\x99\x99\x99\x99\xf1?\x9a\x99\x99\x99\x99\x99\x01@ffffff\n@'
Warning: discarding nonzero nanoseconds
